// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myuqwolfrykuspikkurr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dXF3b2xmcnlrdXNwaWtrdXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Mjc3NzgsImV4cCI6MjA3MzEwMzc3OH0.jy8-u3lsOcdIVcw40VfiYI3gNJw5aZKxG4NxbE1y94E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});